home/urls.py
from django.urls import path
from .views import *
app_name = 'home'
urlpatterns = [
    path('', index, name="index"),
    path('videos_list/', videos_list, name="videos_list"),
    path('PDF_Book_list/', PDF_Book_list, name="PDF_Book_list"),
   
]

sinna/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),

    path('profile/', views.profile, name='profile'),

    # Authentication
    path('users/login/', views.UserLoginView.as_view(), name='login'),
    path('users/logout/', views.logout_view, name='logout'),
    path('users/register/', views.register, name='register'),
    path('users/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('users/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name="password_change_done"),
    path('users/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('users/password-reset-confirm/<uidb64>/<token>/', 
        views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('users/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('users/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ROOT_DIR/templates/_base.html
{% load static %}

<!doctype html>
<html class="no-js " lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">
    <title>SINAA | Learn Chinese language  </title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="{% static 'light/assets//plugins/bootstrap/css/bootstrap.min.css' %}">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'light/assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'light/assets/css/color_skins.css' %}">
</head>

<body class="theme-cyan">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="m-t-30"><img class="zmdi-hc-spin" src="{% static 'light/assets/images/logo.svg' %}" width="48" height="48" alt="Oreo"></div>
            <p>Welcom To Sinna  ...</p>
        </div>
    </div>
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>

    {% include 'navbar.html' %}
    {% include 'Sidebar.html' %}
    {% include 'right_sidebar.html' %}
   <!-- Main Content -->

    {% block header %}

    {% endblock header %}
    

    {% block content %}
    {% endblock content %}




  <!-- Jquery Core Js -->
  <script src="{% static 'light/assets/bundles/libscripts.bundle.js' %}"></script>
  <!-- Lib Scripts Plugin Js -->
  <script src="{% static 'light/assets/bundles/vendorscripts.bundle.js' %}"></script>
  <!-- Lib Scripts Plugin Js -->

  <script src="{% static 'light/assets/bundles/knob.bundle.js' %}"></script>
  <!-- Custom Js -->
  <script src="{% static 'light/assets/bundles/mainscripts.bundle.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/widgets/infobox/infobox-1.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/charts/jquery-knob.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/cards/basic.js' %}"></script>

</body>

</html>

ROOT_DIR/templates/navbar.html
{% load static %}
       <!-- Top Bar -->
       <nav class="navbar p-l-5 p-r-5">
        <ul class="nav navbar-nav navbar-left">
            <li >
                
                    <a href="javascript:void(0);" class="bars"></a>
                    <a class="mega-menu" ><img src="{% static 'light/assets/images/logo.svg' %}" width="30" alt="Sinna"><span class="m-l-10">
                        <p> <strong> Welcom To Sinna</strong>
                            <small>Learning chinease Lang</small>
                            </p>
                    </span></a>
                
            </li>
           
                

           
         
            <li class="float-right">
                {%if user.is_authenticated%}
             
                    <a class="mega-menu" href="{%url 'users:password_change'%}">Change password</a>
                    <a class="mega-menu" href="{% url 'users:logout' %}">logout</a>
                    {%else%}
                    
                    <a class="mega-menu" href="{% url 'users:login' %}">Login</a>
                    <a class="mega-menu" href="{% url 'users:register' %}">Signup</a>
                    {%endif%}
                
                <a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="zmdi zmdi-settings zmdi-hc-spin"></i></a>
            </li>
        </ul>
    </nav>

ROOT_DIR/templates/right_sidebar.html
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#setting"><i
                        class="zmdi zmdi-settings zmdi-hc-spin"></i></a></li>
            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#chat"><i
                        class="zmdi zmdi-comments"></i></a></li>
            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#activity">Activity</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane slideRight active" id="setting">
                <div class="slim_scroll">
                    <div class="card">
                        <h6>Skins</h6>
                        <ul class="choose-skin list-unstyled">
                            <li data-theme="purple" class="active">
                                <div class="purple"></div>
                            </li>
                            <li data-theme="blue">
                                <div class="blue"></div>
                            </li>
                            <li data-theme="cyan">
                                <div class="cyan"></div>
                            </li>
                            <li data-theme="green">
                                <div class="green"></div>
                            </li>
                            <li data-theme="orange">
                                <div class="orange"></div>
                            </li>
                            <li data-theme="blush">
                                <div class="blush"></div>
                            </li>
                        </ul>
                    </div>
                    <div class="card theme-light-dark">
                        <h6>Left Menu</h6>
                        <button class="t-light btn btn-default btn-simple btn-round btn-block">Light</button>
                        <button class="t-dark btn btn-default btn-round btn-block">Dark</button>
                        <button class="m_img_btn btn btn-primary btn-round btn-block">Sidebar Image</button>
                    </div>
                
                   
                </div>
            </div>
         
        </div>
    </aside>

ROOT_DIR/templates/sidebar.html
{% load static %}
<aside id="leftsidebar" class="sidebar">
  
    <div class="tab-content">
       
        <div class="tab-pane stretchLeft active" id="user">
            <div class="menu">
                <ul class="list">
                    
                    <li>
                     
                        <div class="user-info">
                            {%if user.is_authenticated%}
                            {% if user.profile.avatar == '' %}
                            <div class="image"><a  class=" waves-effect "><img src="{% static 'assets/images/profile_av.jpg' %}" alt="User"></a></div>
                            {% else %}
                            <div class="image"><a  class=" waves-effect "><img src="{{ user.profile.avatar.url  }}" alt="User"></a></div>
                            {% endif %}
                            {% else %}
                            <div class="image"><a  class=" waves-effect "><img src="{% static 'assets/images/profile_av.jpg' %}" alt="User"></a></div>
                            {% endif %}
                            <div class="detail">
                                <h4>{{ user.profile  }}</h4>
                                <small>{{ user.profile  }}</small>
                            </div>
                            <a title="facebook" href="javascript:void(0);"><i class="zmdi zmdi-facebook"></i></a>
                            <a title="twitter" href="javascript:void(0);"><i class="zmdi zmdi-twitter"></i></a>
                            <a title="instagram" href="javascript:void(0);"><i class="zmdi zmdi-instagram"></i></a>
                        </div>
                    </li>
                    {% if request.user.is_superuser %}
                    <li class="active"> <a href="/admin" class="menu-toggle"><i class="zmdi zmdi-home"></i><span>Admin Panel</span></a>
                       
                    </li>
                    {% endif %}

                    <li class="active"> <a href="{% url 'home:index' %}" class="menu"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a>
                           
                    </li>

                    <li class="active"> <a href="{% url 'users:profile' %}" class="menu"><i class="zmdi zmdi-account "></i><span>Profile  </span></a>
                           
                    </li>


                    <li class="active"> <a href="{% url 'home:PDF_Book_list' %}" class="menu"><span class="icon-name">PDF_Book_list</span> </a>
                           
                    </li>
                    
                    <li class="active"> <a href="{% url 'home:videos_list' %}" class="menu">  <span class="icon-name">Video</span></a>

                        {% for cat in cat %}
                    <li class="active"> <a href="" class="menu">  <span class="icon-name">{{cat.category_name}}</span></a>
                        {% endfor %}
                     
                    </li>
                      
                  
                   
                </ul>
            </div>
        </div>
    </div>
</aside>