home/urls.py
from django.urls import path
from .views import *
app_name = 'home'
urlpatterns = [
    path('', index, name="index"),
    path('videos_list/', videos_list, name="videos_list"),
    path('PDF_Book_list/', PDF_Book_list, name="PDF_Book_list"),
   
]

sinna/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),

    path('profile/', views.profile, name='profile'),

    # Authentication
    path('users/login/', views.UserLoginView.as_view(), name='login'),
    path('users/logout/', views.logout_view, name='logout'),
    path('users/register/', views.register, name='register'),
    path('users/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('users/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name="password_change_done"),
    path('users/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('users/password-reset-confirm/<uidb64>/<token>/', 
        views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('users/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('users/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

from django.conf import settings

from django.conf.urls.static import static

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver


def Path_Users_Avatar_Profile(instance,filename):
    return "User_Profile/%s/user-img.jpeg"%(instance.user.id )





class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "ADMIN", "Admin"
        STUDENT = "STUDENT", "Student"
        TEACHER = "TEACHER", "Teacher"

    base_role = Role.STUDENT
    role = models.CharField(max_length=50, choices=Role.choices , default=base_role)
   

class USERSTUDENTTManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.STUDENT)


class User_STUDENT(User):

    base_role = User.Role.STUDENT

    STUDENT = USERSTUDENTTManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for Uer"
    


class TEACHERManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.TEACHER)


class User_TEACHER(User):

    base_role = User.Role.TEACHER

    TEACHER = TEACHERManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for TEACHER"






def Path_Profile_Avatar(instance,filename):
    

    return "media/%s/Users/avataer/%s/avatar.jpeg"%(instance.user.id ,instance.user.id)

   
class Profile(models.Model):
    class Gender_Role(models.TextChoices):
        MALE = "MALE", "Male"
        FEMALE = "FEMALE", "Female"

    
    user = models.OneToOneField(User, on_delete=models.CASCADE , related_name='profile')
    bio = models.CharField(max_length=50, blank=True)
    avatar = models.FileField(upload_to=Path_Profile_Avatar)
    birthday = models.DateField(null=True, blank=True)
    gender_role = Gender_Role.MALE
    gender = models.CharField(max_length=50, choices=Gender_Role.choices , default=gender_role)
    def __str__(self):
       fir = str(self.user)
       if not self.user.first_name   :
           return fir
       else :
        return '%s %s' % (self.user.first_name, self.user.last_name)
    @property
    def get_avatar(self):
        return self.avatar.url if self.avatar else static('img/team/default-profile-picture.png')
  

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UsernameField, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import *

class RegistrationForm(UserCreationForm):
  password1 = forms.CharField(
      label=_("Password"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
  )
  password2 = forms.CharField(
      label=_("Password Confirmation"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Confirmation'}),
  )

  class Meta:
    model = User
    fields = ('username', 'email', )

    widgets = {
      'username': forms.TextInput(attrs={
          'class': 'form-control',
          'placeholder': 'Username'
      }),
      'email': forms.EmailInput(attrs={
          'class': 'form-control',
          'placeholder': 'Email'
      })
    }


class LoginForm(AuthenticationForm):
  username = UsernameField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
  password = forms.CharField(
      label=_("Password"),
      strip=False,
      widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}),
  )

class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))

class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")
    

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Old Password'
    }), label='Old Password')
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")



class UpdateUserForm(forms.ModelForm):
 
    class Meta:
        model = User
        fields = ['first_name',  'email' ,  'last_name']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    class Meta:
        model = Profile
        fields = ['avatar', 'gender' , 'birthday']
        widgets = {
    'birthday': forms.DateInput( format=('%Y-%m-%d'), attrs={'class': 'form-control' , 'type': 'date' }),}


class ProfileForm(forms.ModelForm):
  
    class Meta:
        model = Profile
        fields = ('avatar', 'birthday' , 'gender' )
        widgets = {
    'birthday': forms.DateInput( format=('%Y-%m-%d'), attrs={'class': 'form-control' , 'type': 'date' }),}

def form_validation_error(form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field, 'label') else 'Error', error)
    return msg

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView, PasswordResetConfirmView
from .forms import *
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
# Create your views here.

# Pages
def index(request):

  return render(request, 'pages/profile.html', { 'segment': 'index' })


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('users:profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})

# Authentication
class UserLoginView(LoginView):
  template_name = 'users/login.html'
  form_class = LoginForm

def register(request):
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
      form.save()
      print('Account created successfully!')
      return redirect('users:login')
    else:
      print("Register failed!")
  else:
    form = RegistrationForm()

  context = { 'form': form }
  return render(request, 'users/register.html', context)

def logout_view(request):
  logout(request)
  return redirect('users:login')

class UserPasswordResetView(PasswordResetView):
  template_name = 'users/password_reset.html'
  form_class = UserPasswordResetForm

class UserPasswordResetConfirmView(PasswordResetConfirmView):
  template_name = 'users/password_reset_confirm.html'
  form_class = UserSetPasswordForm

class UserPasswordChangeView(PasswordChangeView):
  template_name = 'users/password_change.html'
  form_class = UserPasswordChangeForm

users/templates/users/authentication_base.html
{% load static %}


<!doctype html>
<html class="no-js " lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">

    <title>SINAA | Learn Chinese language  :: Sign In</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'light/assets//plugins/bootstrap/css/bootstrap.min.css' %}">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'light/assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'light/assets/css/authentication.css' %}">
    <link rel="stylesheet" href="{% static 'light/assets/css/color_skins.css' %}">

</head>

<body class="theme-purple authentication sidebar-collapse">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-transparent">
        <div class="container">
            <div class="navbar-translate n_logo">
                <a class="navbar-brand" href="javascript:void(0);" title="" target="_blank">Sinna</a>
                <button class="navbar-toggler" type="button">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
            </div>
            <div class="navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">Home</a>
                    </li>
                  
                    <li class="nav-item">
                        <a class="nav-link" title="Follow us on Twitter" href="javascript:void(0);" target="_blank">
                        <i class="zmdi zmdi-twitter"></i>
                        <p class="d-lg-none d-xl-none">Twitter</p>
                    </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" title="Like us on Facebook" href="javascript:void(0);" target="_blank">
                        <i class="zmdi zmdi-facebook"></i>
                        <p class="d-lg-none d-xl-none">Facebook</p>
                    </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" title="Follow us on Instagram" href="javascript:void(0);" target="_blank">                        
                        <i class="zmdi zmdi-instagram"></i>
                        <p class="d-lg-none d-xl-none">Instagram</p>
                    </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-white btn-round" href="{% url 'users:register' %}" >SIGN UP</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="page-header">
        <div class="page-header-image" style="background-image:url({% static 'light/assets/images/login.jpg' %})"></div>
        <div class="container">
            <div class="col-md-12 content-center">
                <div class="card-plain">
                 
                    {% block authentication %}

                    {% endblock authentication %}

                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <nav>
                    <ul>
                        <li><a  >Contact Us</a></li>
                        <li><a>About Us</a></li>
                       
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>,
                   
                </div>
            </div>
        </footer>
    </div>

    <!-- Jquery Core Js -->
    
  <!-- Jquery Core Js -->
  <script src="{% static 'light/assets/bundles/libscripts.bundle.js' %}"></script>
  <!-- Lib Scripts Plugin Js -->
  <script src="{% static 'light/assets/bundles/vendorscripts.bundle.js' %}"></script>
  <!-- Lib Scripts Plugin Js -->

  <script src="{% static 'light/assets/bundles/knob.bundle.js' %}"></script>
  <!-- Custom Js -->
  <script src="{% static 'light/assets/bundles/mainscripts.bundle.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/widgets/infobox/infobox-1.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/charts/jquery-knob.js' %}"></script>
  <script src="{% static 'light/assets/js/pages/cards/basic.js' %}"></script>
    <!-- Lib Scripts Plugin Js -->

    <script>
        $(".navbar-toggler").on('click', function() {
            $("html").toggleClass("nav-open");
        });
        //=============================================================================
        $('.form-control').on("focus", function() {
            $(this).parent('.input-group').addClass("input-group-focus");
        }).on("blur", function() {
            $(this).parent(".input-group").removeClass("input-group-focus");
        });
    </script>
</body>

</html>

users/templates/users/login.html
{% extends 'users/authentication_base.html' %}
{% load static %}
{% block authentication %}


<form role="form" method="post">
    {% csrf_token %}

    {% if form.errors %}
    <div class="alert alert-danger " ">
                                <div id=" form_errors">
        {% for key, value in form.errors.items %}
        <strong>{{ value }}</strong>
        {% endfor %}
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endif %}
    <div class="header">
        <div class="logo-container">
            <img src="{% static 'light/assets/images/logo.svg' %}" alt="">
        </div>
        <h5>Log in</h5>
    </div>
    <div class="content">
        <div class="input-group input-lg">
            <input type="text" class="form-control" placeholder="Enter User Name" name="username">
            <span class="input-group-addon">
                <i class="zmdi zmdi-account-circle"></i>
            </span>
        </div>
        <div class="input-group input-lg">
            <input type="password" placeholder="Password" name="password" class="form-control" />
            <span class="input-group-addon">
                <i class="zmdi zmdi-lock"></i>
            </span>
        </div>
    </div>
    <div class="footer text-center">
        <button type="submit" class="btn btn-primary btn-round btn-lg btn-block ">SIGN IN</button>
        <p>Don't have an account? <a href="{% url 'users:register' %}" class="text-primary">Register</a></p>
    </div>
</form>

{% endblock authentication %}

users/templates/users/profile.html
{% extends '_base.html' %}
{% load static %}
{% block header %}
<div class="block-header">
    <div class="row">

        <div class="col-lg-7 col-md-7 col-sm-12 text-left">

            <ul class="breadcrumb float-md-left">
                <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Home</a></li>
                <li class="breadcrumb-item active">profile</li>
            </ul>
        </div>
    </div>
</div>
{% endblock header %}

{% block content %}

<link rel="stylesheet" href="https://thememakker.com/templates/oreo/html/assets/plugins/multi-select/css/multi-select.css">
<!-- Bootstrap Spinner Css -->
<!-- Bootstrap Tagsinput Css -->
<!-- Bootstrap Select Css -->
<link rel="stylesheet" href="https://thememakker.com/templates/oreo/html/assets/plugins/bootstrap-select/css/bootstrap-select.css" />
<!-- noUISlider Css -->
<!-- Select2 -->
<link rel="stylesheet" href="https://thememakker.com/templates/oreo/html/assets/plugins/select2/select2.css" />
<!-- Custom Css -->
<link rel="stylesheet" href="assets/css/main.css">
<link rel="stylesheet" href="assets/css/color_skins.css">


   
    <div class="row">
        <div class="col-lg-6 ">
            <div class="card">
                <ul class="nav nav-tabs">
                   
                    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#update_profile">update profile</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" data-toggle="tab"
                            href="#change_password">change_password</a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
           
                <div role="tabpanel" class="tab-pane active" id="update_profile">
                    <div class="card">
                        <div class="header">
                            <h2><strong>Account</strong> Settings</h2>
                        </div>
                        <div class="body">
                            <div class="row clearfix">
                                <div class="col-md-12">
                                    <form method="POST" action="{% url 'users:profile' %} " enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row">
                                            {% for field in user_form %}
                                        <div class="col-lg-6 col-md-12">
                                            <div class="form-group">
                                                <input type="{% if field.name == 'password1'%}password{% elif field.name == 'password2'%}password{% elif field.name == 'email' %}email{% else %}text{% endif %}" 
                                                class="form-control" placeholder="Enter {{ field.name }}" name="{{ field.name }}" id="id_{{field.name}}">
                                              
                                            </div>
                                        </div>
    
                                        {% endfor %}    
                                        {{profile_form.avatar}}
                                        <div class="d-md-block text-left">
                                            <div class="font-weight-normal text-dark mb-1">Choose Image</div>
                                            <div class="text-gray small">JPG, GIF or PNG. Max size of 800K</div>
                                        </div>
    
                                   
                                        </div>
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-primary btn-round">Save Changes</button>
                                        </div>
                                    </form>
                                </div>
                              
                            </div>
                        </div>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane " id="change_password">
                    <div class="card">
                        <div class="header">
                            <h2><strong>change </strong> password</h2>
                        </div>
                        <div class="row">
                            <!-- basic form start -->
                            <div class="col-12 mt-5">
                                <div class="card">
                                    <div class="card-body">

                                        {% if message %}
                                        <div class="alert alert-success" role="alert">
                                            {{ message }}
                                        </div>
                                        {% endif %}
                                        {% if form.non_field_errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {% for error in form.non_field_errors %}
                                            {{ error|escape }}<br>
                                            {% endfor %}
                                        </div>
                                        {% endif %}
                                        <form method="POST" action="{% url 'users:password_change' %}">
                                            {% csrf_token %}

                                            <div class="form-group">
                                                <label class="col-form-label" for="id_old_password">Old Password</label>
                                                <input type="password" class="form-control" name="old_password" required
                                                    maxlength="254" id="id_old_password">
                                            </div>

                                            <div class="form-group">
                                                <label class="col-form-label" for="id_new_password1">New
                                                    Password</label>
                                                <input type="password" class="form-control" name="new_password1"
                                                    required maxlength="254" id="id_new_password1">
                                            </div>

                                            <div class="form-group">
                                                <label class="col-form-label" for="id_new_password2">New Password
                                                    Confirmation</label>
                                                <input type="password" class="form-control" name="new_password2"
                                                    required maxlength="254" id="id_new_password2">
                                            </div>

                                            <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                                            <a role="button" class="btn btn-secondary mt-4 pr-4 pl-4"
                                                href="{% url 'users:profile' %}">Back</a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- basic form end -->


                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-xl-6 col-lg-7 col-md-12">
            <div class="card profile-header">
                <div class="header">
                    <h2><strong>change </strong> Avatar</h2>
                </div>
                <div class="body">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-12">
                            {% if user.profile.avatar == '' %}
                            <div class="profile-image float-md-right"><img
                                    src="{% static 'assets/images/profile_av.jpg' %}"></a></div>

                            {% else %}
                            <div class="profile-image float-md-right"><img src="{{ user.profile.avatar.url  }}"></a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="col-lg-8 col-md-8 col-12">
                            <br>
                            <h4 class="m-t-0 m-b-0"><strong>{{ user.profile }}</strong> </h4>
                            <span class="job_post">{{ user.first_name }}</span>
                            <p> {{ user.last_name }} </p>
                            <div>
                                <button class="btn btn-primary btn-round" data-toggle="tab" href="#update_profile">Save</button>
                                
                            </div>
                            <p class="social-icon m-t-5 m-b-0">
                                <a title="Twitter" href="javascript:void(0);"><i class="zmdi zmdi-twitter"></i></a>
                                <a title="Facebook" href="javascript:void(0);"><i class="zmdi zmdi-facebook"></i></a>

                            </p>
                        </div>
                    </div>
                </div>                    
            </div>
        </div>
       
    </div>


{% endblock %}

users/templates/users/register.html
{% extends 'users/authentication_base.html' %}
{% load static %}
{% block authentication %}


<form role="form" method="post">
    {% csrf_token %}


    <div class="header">
        <div class="logo-container">
            <img src="{% static 'light/assets/images/logo.svg' %}" alt="">
        </div>
        <h5>SIGN Up</h5>
    </div>
    <div class="content">
      {% for field in form %}
        <div class="input-group input-lg">
            <input type="{% if field.name == 'password1'%}password{% elif field.name == 'password2'%}password{% elif field.name == 'email' %}email{% else %}text{% endif %}" class="form-control" placeholder="Enter {{ field.name }}" name="{{ field.name }}">
            
            <span class="text-danger">{{ field.errors }}</span>
        </div>
       
        {% endfor %}
       
    </div>
    <div class="footer text-center">
        <button type="submit" class="btn btn-primary btn-round btn-lg btn-block ">SIGN Up</button>
        <hp> have an account? <a href="{% url 'users:login' %}" class="text-primary">login</a></hp>
    </div>
</form>

{% endblock authentication %}